# Form implementation generated from reading ui file 'imagingIav_int.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(453, 307)
        Form.setMinimumSize(QtCore.QSize(453, 307))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.processButton = QtWidgets.QPushButton(parent=Form)
        self.processButton.setObjectName("processButton")
        self.horizontalLayout_2.addWidget(self.processButton)
        self.data_to_tableButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_to_tableButton.sizePolicy().hasHeightForWidth())
        self.data_to_tableButton.setSizePolicy(sizePolicy)
        self.data_to_tableButton.setMinimumSize(QtCore.QSize(90, 26))
        self.data_to_tableButton.setMaximumSize(QtCore.QSize(90, 26))
        self.data_to_tableButton.setObjectName("data_to_tableButton")
        self.horizontalLayout_2.addWidget(self.data_to_tableButton)
        spacerItem = QtWidgets.QSpacerItem(10000, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prevButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevButton.sizePolicy().hasHeightForWidth())
        self.prevButton.setSizePolicy(sizePolicy)
        self.prevButton.setMinimumSize(QtCore.QSize(21, 0))
        self.prevButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout.addWidget(self.prevButton)
        self.image_listView = QtWidgets.QListView(parent=Form)
        self.image_listView.setObjectName("image_listView")
        self.horizontalLayout.addWidget(self.image_listView)
        self.nextButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextButton.sizePolicy().hasHeightForWidth())
        self.nextButton.setSizePolicy(sizePolicy)
        self.nextButton.setMinimumSize(QtCore.QSize(21, 0))
        self.nextButton.setMaximumSize(QtCore.QSize(21, 16777215))
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.processButton.setText(_translate("Form", "Process"))
        self.data_to_tableButton.setText(_translate("Form", "Data to table"))
        self.prevButton.setText(_translate("Form", "<"))
        self.nextButton.setText(_translate("Form", ">"))
