# Form implementation generated from reading ui file 'imaging_roi.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_img_roi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(453, 307)
        Form.setMinimumSize(QtCore.QSize(453, 307))
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.processButton = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.processButton.sizePolicy().hasHeightForWidth())
        self.processButton.setSizePolicy(sizePolicy)
        self.processButton.setMinimumSize(QtCore.QSize(69, 31))
        self.processButton.setMaximumSize(QtCore.QSize(69, 31))
        self.processButton.setObjectName("processButton")
        self.horizontalLayout.addWidget(self.processButton)
        self.boundaries_amountSpinBox = QtWidgets.QSpinBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boundaries_amountSpinBox.sizePolicy().hasHeightForWidth())
        self.boundaries_amountSpinBox.setSizePolicy(sizePolicy)
        self.boundaries_amountSpinBox.setMinimumSize(QtCore.QSize(200, 31))
        self.boundaries_amountSpinBox.setMaximumSize(QtCore.QSize(200, 31))
        self.boundaries_amountSpinBox.setMinimum(1)
        self.boundaries_amountSpinBox.setMaximum(5)
        self.boundaries_amountSpinBox.setObjectName("boundaries_amountSpinBox")
        self.horizontalLayout.addWidget(self.boundaries_amountSpinBox)
        self.shift_amountSpinBox = QtWidgets.QSpinBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shift_amountSpinBox.sizePolicy().hasHeightForWidth())
        self.shift_amountSpinBox.setSizePolicy(sizePolicy)
        self.shift_amountSpinBox.setMinimumSize(QtCore.QSize(125, 31))
        self.shift_amountSpinBox.setMaximumSize(QtCore.QSize(81, 31))
        self.shift_amountSpinBox.setMinimum(30)
        self.shift_amountSpinBox.setMaximum(400)
        self.shift_amountSpinBox.setObjectName("shift_amountSpinBox")
        self.horizontalLayout.addWidget(self.shift_amountSpinBox)
        spacerItem = QtWidgets.QSpacerItem(16777212, 0, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image_graphView = QtWidgets.QGraphicsView(parent=Form)
        self.image_graphView.setObjectName("image_graphView")
        self.horizontalLayout_2.addWidget(self.image_graphView)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.processButton.setText(_translate("Form", "Process"))
        self.boundaries_amountSpinBox.setPrefix(_translate("Form", "Boundaries amount:   "))
        self.shift_amountSpinBox.setPrefix(_translate("Form", "Shift:   "))
